# Generated by Django 5.1 on 2024-08-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='list_of_todos',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.todo'),
        ),
    ]
