# Generated by Django 5.1 on 2024-08-17 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_list_of_todos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='list_of_todos',
        ),
    ]
